### PR TITLE
Allow API URLs to be overridden

### LINKED ISSUE #6: Configurable Travis CI API endpoint
Hey @alrra,

it would be cool if users could define the Travis CI API endpoint that should be used.
Currently this module won't work with private/enterprise Travis versions.

The python version solves this with arguments passed: https://github.com/dmakhno/travis_after_all/blob/master/travis_after_all.py#L22-L23
I think this could be configureable with environment variables, or options passed to the `require`d module.

Please let me know what you think; I'm happy to help to get this going.

Best,
Stephan

### LINKED ISSUE #14: Failed to parse JSON
I'm trying to use the JavaScript interface to travis-after-all and I'm getting the following on every build:
```
[travis-after-all] Job succeeded (a0d...)
[travis-after-all] Failed to parse JSON from "https://api.travis-ci.org/builds/195...".
Error: Unexpected end of input
Failed to parse JSON from "https://api.travis-ci.org/builds/195...".
Error: Unexpected end of input
SyntaxError: Failed to parse JSON from "https://api.travis-ci.org/builds/195...".
Error: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/travis/build/fastly/Tango/node_modules/travis-after-all/lib/travis-after-all.js:120:31)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
The project is on the private, hosted version of Travis. Perhaps there's a different API endpoint?

### PR DESCRIPTION
**Pull request by jamesarosen**
https://docs.travis-ci.com/api/ lists the URLs for various Travis environments. This allows the library consumer to specify the correct URLs for the project's environment.

Closes #6
Closes #14

### CODE REVIEW

**Comment by jamesarosen** [comment]
This doesn't have support for the command-line version. It wouldn't be hard to add argument parsing in the "if this script is called directly" block, but it's not necessary for my use-case.

**Comment by jamesarosen** [comment]
I actually don't love this implementation because the user needs to parse the build number. I'll try again.

**Comment by jamesarosen** [comment]
Second attempt pushed.

**Comment by jamesarosen** [comment]
With this I see
```
[travis-after-all] Failed to parse JSON from "https://api.travis-ci.com/jobs/303...".
Error: Unexpected token o
Failed to parse JSON from "https://api.travis-ci.com/jobs/303...".
Error: Unexpected token o
SyntaxError: Failed to parse JSON from "https://api.travis-ci.com/jobs/303...".
Error: Unexpected token o
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/travis/build/fastly/Tango/node_modules/travis-after-all/lib/travis-after-all.js:121:31)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by alrra** [comment]
@jamesarosen Thanks for starting the work on this, really appreciate it!

Cc: @gr2m, @boennemann.

--

> We may need to add GitHub OAuth support for private repos.

From [my previous comment](https://github.com/alrra/travis-after-all/issues/6#issuecomment-152770686):

> From http://docs.travis-ci.com/api/#overview: 
> > The first thing you will have to find out is the correct API endpoint to use.

> >  * Travis CI for open source: For open source projects tested on travis-ci.org, use https://api.travis-ci.org.
> >  * Travis Pro: For private projects tested on travis-ci.com, use https://api.travis-ci.com.
> >  * Travis Enterprise: For projects running on a custom setup, use https://travis.example.com/api (where you replace travis.example.com with the domain Travis CI is running on).

> > **Note that both Pro and Enterprise will require almost all API calls to be authenticated.**

> :arrow_up: It seems that the authentication part also needs to be done.

**Comment by jamesarosen** [comment]
This now _theoretically_ has support for the Travis access token. I haven't yet gotten it working on my project.

**Comment by jamesarosen** [comment]
I was using the wrong token (`travis token` instead of `travis token --pro`). This now works :)

**Comment by alrra** [comment]
@jamesarosen I pulled your changes on a branch [in order to test](https://github.com/alrra/travis-after-all/blob/b5d8b448e287709c1aadaef2e6a02ad5717ae2b3/test/main.js#L40-L54) that everything that worked before still works, and it seems [that is the case](https://travis-ci.org/alrra/travis-after-all/builds/101324032)! :tada: :purple_heart: 

I will review this in more detail (e.g.: see if there is the possibility of the token leaking) and make some other changes, but that will probably happen after next week. Sorry about the delay. :disappointed:

**Comment by luisatlive** [comment]
Looking forward to trying this out!

**Comment by gr2m** [comment]
@alrra any chance we could get this merged? It looks like it’s one thing that is blocking `semantic-release` to release its v6.3 to the `@latest` dist tag. I’m happy to help if there is anything I can do? /cc @boennemann

**Comment by alrra** [comment]
Note: I've deprecated this project as the functionality it provided is now supported natively by `Travis CI` via [`Build Stages`](https://blog.travis-ci.com/2017-05-11-introducing-build-stages).

**Pull request closed without merging**
